# Generated by Django 5.1.7 on 2025-04-29 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cusine_name', models.CharField(max_length=255)),
                ('cusine_description', models.TextField()),
                ('type', models.CharField(choices=[('VEG', 'VEG'), ('NON VEG', 'NON VEG')], max_length=20)),
                ('region', models.CharField(choices=[('NORTH INDIAN', 'NORTH INDIAN'), ('SOUTH INDIAN', 'SOUTH INDIAN'), ('PUNJABI FOOD', 'PUNJABI FOOD'), ('FAST FOOD', 'FAST FOOD'), ('DESSERT', 'DESSERT'), ('SNACK', 'SNACK'), ('REGIONAL SPECIAL', 'REGIONAL SPECIAL')], max_length=20)),
                ('price', models.IntegerField()),
                ('time', models.IntegerField()),
                ('cusine_image', models.ImageField(upload_to='images/cusine_images/')),
            ],
        ),
    ]
