# Generated by Django 5.1.7 on 2025-05-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
