# Generated by Django 5.1.7 on 2025-05-12 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_userprofile_mobile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCreated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('delivery_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('delivered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_received', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_started', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_cooking_completed', models.BooleanField(default=False)),
                ('cooking_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_out_for_delivery', models.BooleanField(default=False)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('otp_confirmed', models.BooleanField(default=False)),
                ('delivery_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cuisine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.ordercreated')),
            ],
        ),
        migrations.AddField(
            model_name='ordercreated',
            name='items',
            field=models.ManyToManyField(related_name='ordered_in', through='adminapp.OrderItem', to='adminapp.cuisine'),
        ),
    ]
