# Generated by Django 5.1.7 on 2025-05-16 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_ordercreated_orderitem_ordercreated_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField()),
                ('driver_image', models.ImageField(upload_to='images/driver_images/')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
            ],
        ),
    ]
