# Generated by Django 5.1.7 on 2025-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_driver_user_driver_username_driver_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.CharField(blank=True, default='driver', max_length=16, null=True),
        ),
    ]
