# Generated by Django 5.1.7 on 2025-05-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_driver_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercreated',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='adminapp.driver'),
        ),
    ]
