# Generated by Django 5.1.7 on 2025-05-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_ordercreated_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
