# Generated by Django 5.1.7 on 2025-05-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_usercart_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
