# Generated by Django 5.1.7 on 2025-05-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usercart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='is_ordered',
        ),
    ]
