# Generated by Django 5.1.7 on 2025-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usercart_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
