# Generated by Django 5.1.7 on 2025-05-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_usercart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='total_amount',
        ),
    ]
