# Generated by Django 5.1.7 on 2025-05-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_usercart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='is_ordered',
        ),
    ]
